maplibre support for Qt6 and MSVC 2019
maplibre/maplibre-gl-native pull request #125
Opened 2021-07-11 20:46 UTC by dpaulat

Update maplibre-gl-native to compile using Qt 6.1.1 and MSVC 2019

@ntadej should probably have his PR merged first:
https://github.com/maplibre/maplibre-gl-native/pull/118

Once his is merged, I'll work to resolve any conflicts.

2021-07-11 20:47 UTC, dpaulat commented
Open issues are:
- https://github.com/maplibre/maplibre-gl-native/issues/124
- Missing zlib dependency, currently must be resolved externally

2021-07-11 21:53 UTC, ntadej commented
Thanks @dpaulat!

I have also been playing with this a bit and I have some additional fixes prepared, namely:
 - One can use icu support and zlib from Qt
 - I did some cleanup of the CMake configuration (but can wait for this MR to go in)
 - I fixed various warnings

2021-07-17 04:42 UTC, dpaulat commented
With #118 merged, I rebased and resolved conflicts.  This PR is ready for review.

2021-07-19 22:04 UTC, ntadej requested changes

2021-07-20 01:40 UTC, dpaulat commented on platform/qt/qt.cmake
> +                        OpenGLWidgets
Just these specific components?  I'd need to do some digging to figure out what this should be.  If you have an idea of what this should be, I can leave this to you.

https://doc.qt.io/qt-5/cmake-get-started.html

2021-07-22 12:32 UTC, klokan commented
This looks like a great activity @dpaulat & @ntadej. 👍  Thank you very much for looking into this.

Is there a first demo app? Or do you develop that for some particular project of yours?
 
@petr-pokorny-1 Could you please check the code and provide your comments in a review - once you are back from holiday?
 
BTW We could then eventually update https://www.maptiler.com/news/2019/04/using-maptiler-maps-inside-qt/ or reuse the older sample app at https://github.com/maptiler/maptiler-qml-demo to demo the functionality - esp. if there is no other demo app.

2021-07-22 12:37 UTC, dpaulat commented
Thank you!  There is a subproject in this repository called mbgl-qt that provides demo functionality.  I can post a screenshot this evening.

2021-07-22 12:39 UTC, ntadej commented
> Is there a first demo app? Or do you develop that for some particular project of yours?

I have a hobby project where I already had to patch existing Mapbox implementation and having something standalone and independent from Qt releases would be much more useful.

Also I'm happy to develop the revised version of QML plugin under the MapLibre umbrella. I have a prototype ready but I'm still cleaning up and streamlining the build system (some more MRs incoming). https://github.com/ntadej/qt-geoservices-maplibre

2021-07-23 02:55 UTC, dpaulat commented
> Thank you! There is a subproject in this repository called mbgl-qt that provides demo functionality. I can post a screenshot this evening.

![2021-07-22 21_53_30-Mapbox GL_ Basic](https://user-images.githubusercontent.com/2886605/126732478-b66d705c-3f77-478d-852b-9b1ee332730c.png)

2021-07-25 17:09 UTC, petr-pokorny-1 commented
@dpaulat it looks like your changes are causing Android and iOS SDKs fails to compile. It is mostly due to changes you made in constructor/methods signatures. Do you have Android/iOS dev environment to fix these issues?

2021-07-25 17:11 UTC, ntadej commented
> @dpaulat it looks like your changes are causing Android and iOS SDKs fail to compile. It is mostly due to changes you made in constructor/methods signatures. Do you have Android/iOS dev environment to fix these issues?

I think this commit should fix it: https://github.com/ntadej/maplibre-gl-native/commit/5bedf45eceecfd650046a555f852dae1311f0fcb

2021-07-25 17:12 UTC, dpaulat commented
I will work to spin up an Android environment and see what happened. Hopefully the Android and iOS errors are the same, since I don't have a suitable environment for that.
________________________________
From: Petr Pokorny ***@***.***>
Sent: Sunday, July 25, 2021 12:09:35 PM
To: maplibre/maplibre-gl-native ***@***.***>
Cc: Dan Paulat ***@***.***>; Mention ***@***.***>
Subject: Re: [maplibre/maplibre-gl-native] maplibre support for Qt6 and MSVC 2019 (#125)


@dpaulat<https://github.com/dpaulat> it looks like your changes are causing Android and iOS SDKs fails to compile. It is mostly due to changes you made in constructor/methods signatures. Do you have Android/iOS dev environment to fix these issues?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/maplibre/maplibre-gl-native/pull/125#issuecomment-886231326>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAWAXTOR7765CH4OCLD7TWDTZRAM7ANCNFSM5AFUJECA>.

2021-07-25 17:13 UTC, dpaulat commented
Even better. I will get this cherry picked when I get back to my computer.
________________________________
From: Tadej Novak ***@***.***>
Sent: Sunday, July 25, 2021 12:11:29 PM
To: maplibre/maplibre-gl-native ***@***.***>
Cc: Dan Paulat ***@***.***>; Mention ***@***.***>
Subject: Re: [maplibre/maplibre-gl-native] maplibre support for Qt6 and MSVC 2019 (#125)


@dpaulat<https://github.com/dpaulat> it looks like your changes are causing Android and iOS SDKs fail to compile. It is mostly due to changes you made in constructor/methods signatures. Do you have Android/iOS dev environment to fix these issues?

I think this commit should fix it: ***@***.***<https://github.com/ntadej/maplibre-gl-native/commit/5bedf45eceecfd650046a555f852dae1311f0fcb>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/maplibre/maplibre-gl-native/pull/125#issuecomment-886231558>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAWAXTO2KJ5KPLNAQ4WDSJDTZRAUDANCNFSM5AFUJECA>.

2021-07-25 17:14 UTC, petr-pokorny-1 commented
@ntadej @dpaulat Great - thanks guys!

2021-07-28 19:13 UTC, petr-pokorny-1 approved these changes
Looks good to me. A lot of work, thanks!

2021-07-28 19:15 UTC, petr-pokorny-1 commented
Any chance to write CI workflow for QT and Windows (similar to those in /.github/workflows) ?

2021-07-28 19:18 UTC, ntadej commented
I have something prepared for Mac, android and windows. Plan to open a MR when my other changes will be merged.

I will be on vacation now for two weeks so after this one is merged, I will probably just open one or two MRs.

2021-08-07 03:17 UTC, dpaulat commented
Any other actions for this PR prior to merge?  Thanks!

2021-08-07 15:10 UTC, merged

2021-08-07 15:10 UTC, roblabs commented
This was a lot of work!  Thanks for contributing to MapLibre & FOSS4G.  Looking forward to the CI workflows for GitHub as well.   I reviewed the iOS build for extra warnings (there were none).