Fix street label appearance while animating near zoom level threshhold
maplibre/maplibre-gl-native pull request #267
Opened 2022-03-31 21:57 UTC by nvanfleet

We were seeing some issues while following the users location along a route in the map view that some screen elements (for the most part the labels of street names on the map) would flash in and out.
While it took a long time to determine why this was happening we determined that the issue was simple. We were animating the map camera at a specific zoom level (zoom levels are from 1-25 floats) and the map SDK was sometimes finding us at zoom level 10.0 and sometimes finding us at zoom level 9.9999
This would generally not be a problem except at that particular zoom level we had our map style show the street labels on the map. So when we were at 9.9999 it would hide them, and on the next frame it would have us at 10.0.
The ultimate fix was fairly simple and the zoom level is basically rounded if it is close enough to a rounded zoom level.

2022-03-31 21:58 UTC, nvanfleet commented
This investigation and fix were actually by @junwu-lyft and I am just creating this for him

2022-03-31 21:59 UTC, nvanfleet commented
@junwu-lyft and I are happy to discuss some other solutions to this issue.

2022-04-02 08:30 UTC, ntadej commented
Thank you for your contribution!

Wrong commit though? It looks like #266

2022-04-02 16:44 UTC, nvanfleet commented
@ntadej welp sorry about that I grabbed the wrong patch somehow and didn't notice 😓

2022-04-03 10:16 UTC, ntadej requested changes
I like the idea, I only have a few minor comments.

2022-04-03 10:16 UTC, ntadej commented on src/mbgl/map/transform_state.cpp
> +const double kEpsilon = 1e-9;
Maybe `constexpr double`?

2022-04-03 10:16 UTC, ntadej commented on src/mbgl/map/transform_state.cpp
> +    double round_x = round(x);
`std::round`

2022-04-03 10:16 UTC, ntadej commented on src/mbgl/map/transform_state.cpp
> +    double diff = fabs(round_x - x);
`std::abs`

2022-04-03 10:17 UTC, ntadej commented
Also to add, I've been recently cleaning the remaining warnings from MSVC and it seems that `float` vs `double` accuracy is quite arbitrary in many cases. It would be interesting to see if it's good enough if we go to single precision in most of the cases, which may also solve such issues.

Of course in the meantime this fix is appreciated and useful.

2022-04-05 00:01 UTC, junwu-lyft commented on src/mbgl/map/transform_state.cpp
> +const double kEpsilon = 1e-9;
done

2022-04-05 00:01 UTC, junwu-lyft commented on src/mbgl/map/transform_state.cpp
> +    double round_x = round(x);
done

2022-04-05 00:01 UTC, junwu-lyft commented on src/mbgl/map/transform_state.cpp
> +    double diff = fabs(round_x - x);
done

2022-04-06 21:44 UTC, ntadej approved these changes

2022-04-06 21:44 UTC, merged

2022-07-01 14:58 UTC, wipfli commented
Thanks for this fix @nvanfleet. Can you add a changelog item?

2022-07-01 15:00 UTC, wipfli commented
Ah I see https://github.com/maplibre/maplibre-gl-native/blob/main/CHANGELOG.md has not really been touch since the fork. What is our policy for changelogs?