Suppress unused-but-set-variable in benchmark/
maplibre/maplibre-gl-native pull request #273
Opened 2022-04-18 20:38 UTC by erik

In recent versions of `clang`, the code in `benchmark/` will fail to
build, due to the `unused-but-set-variable` warning.

Tested the patch fixes the build for me with:

```
Apple clang version 13.1.6 (clang-1316.0.21.2.3)
Target: x86_64-apple-darwin21.4.0
```

2022-04-18 20:55 UTC, ntadej commented
Thanks for the contribution!

Should we rather just remove the problematic variable? I am not sure silencing warnings is the best way forward.

2022-04-18 21:42 UTC, erik commented
Good question - the affected code blocks looks [like this](https://github.com/maplibre/maplibre-gl-native/blob/main/benchmark/util/tilecover.benchmark.cpp#L14-L17):

``` cpp
    std::size_t length = 0;
    while (state.KeepRunning()) {
        auto count = util::tileCount(sanFrancisco, 10);
        length += count;
    }
```

Presumably the intention is just so that the function calls aren't optimized away?

If there's a cleaner way of re-writing the benchmark code I can do that instead, figured that scoping the suppression to the benchmark directory only wouldn't be too problematic.

2022-04-20 14:06 UTC, ntadej requested changes
I think we can live with just ignoring this warning for the benchmarks target. Can you try if this works?

2022-04-20 14:06 UTC, ntadej commented on benchmark/CMakeLists.txt
> +    INTERFACE
```suggestion
    PRIVATE
```

2022-04-20 14:25 UTC, erik commented on benchmark/CMakeLists.txt
> +    mbgl-compiler-options
Doesn't appear to work, I see the original errors with this change:

```
vector_tile.benchmark.cpp:12:21: error: variable 'length' set but not used [-Werror,-Wunused-but-set-variable]
```

`-Wno-error=unused-but-set-variable` does not appear in the build command.

2022-04-20 14:31 UTC, erik commented
I removed all build artifacts and tried rerunning the `cmake` commands with the patch below, but ended up with the same original compilation error due to the `unused-but-set` warning.

``` diff
diff --git a/benchmark/CMakeLists.txt b/benchmark/CMakeLists.txt
index a09da5789..b7e24fc64 100644
--- a/benchmark/CMakeLists.txt
+++ b/benchmark/CMakeLists.txt
@@ -25,8 +25,8 @@ target_include_directories(
 )

 target_compile_options(
-    mbgl-compiler-options
-    INTERFACE
+    mbgl-benchmark
+    PRIVATE
         $<$<CXX_COMPILER_ID:AppleClang>:-Wno-error=unused-but-set-variable>
 )
```

2022-07-04 20:24 UTC, ntadej commented
Sorry for taking me this long to get back to this. The issue is the ordering of the options.

As I'm hesitant to silence the warnings I propose to just use `(void)length;` for each occurance. Do you want to do it?

2022-07-05 05:58 UTC, erik commented
No worries at all, I already have a commit doing exactly that from a few months ago. Will update this branch to point to it

2022-07-05 16:27 UTC, ntadej commented
Thank you very much @erik! This looks OK for me now (especially as it is for a test).

2022-07-05 16:27 UTC, merged