Fix render tests
maplibre/maplibre-gl-native pull request #351
Opened 2022-07-04 19:32 UTC by wipfli

This pull request reverts some changes of #270 which broke the render tests.

Probably the syntax has to be adapted.

2022-07-04 19:34 UTC, wipfli commented
Instead of running all render tests, one can only run the ones which currently fail on main with a `run-render-tests.sh` script on linux which might look like this:

```sh
#!/bin/bash
cmake --build build -j $(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null)
./build/mbgl-render-test-runner --manifestPath metrics/linux-clang8-release-style.json --filter "render-tests/symbol-placement/line-overscaled"
./build/mbgl-render-test-runner --manifestPath metrics/linux-clang8-release-style.json --filter "render-tests/symbol-visibility/visible"
./build/mbgl-render-test-runner --manifestPath metrics/linux-clang8-release-style.json --filter "render-tests/text-variable-anchor/rotated-offset"
./build/mbgl-render-test-runner --manifestPath metrics/linux-clang8-release-style.json --filter "render-tests/text-variable-anchor/all-anchors-tile-map-mode"
./build/mbgl-render-test-runner --manifestPath metrics/linux-clang8-release-style.json --filter "query-tests/circle-radius/tile-boundary"
./build/mbgl-render-test-runner --manifestPath metrics/linux-clang8-release-style.json --filter "query-tests/fill-features-in/default"
./build/mbgl-render-test-runner --manifestPath metrics/linux-clang8-release-style.json --filter "query-tests/invisible-features/zero-opacity"
./build/mbgl-render-test-runner --manifestPath metrics/linux-clang8-release-style.json --filter "query-tests/edge-cases/box-cutting-antimeridian-z1"
./build/mbgl-render-test-runner --manifestPath metrics/linux-clang8-release-style.json --filter "query-tests/edge-cases/box-cutting-antimeridian-z0"
./build/mbgl-render-test-runner --manifestPath metrics/linux-clang8-release-style.json --filter "query-tests/edge-cases/null-island"
``` 
This script compiles and then runs the render tests, that were broken by #270. Note that there is one more render test which is broken, something like `enlarge-both`, but this one was already broken before #270...

2022-07-04 19:35 UTC, ntadej requested changes
I will object to this right now. Compared to the other fix, none of these changes (especially the `minSectionLength` one look wrong.

Can you please paste the failing test results?

2022-07-04 19:43 UTC, wipfli commented
On main, 11 tests fail when running `./build/mbgl-render-test-runner --manifestPath metrics/linux-clang8-release-style.json`

Here is the test output: https://wipfli.github.io/debug-maplibre-gl-native/main-linux-clang8-release-style.html

2022-07-04 19:46 UTC, ntadej commented
> On main, 11 tests fail when running `./build/mbgl-render-test-runner --manifestPath metrics/linux-clang8-release-style.json`
> 
> Here is the test output: https://wipfli.github.io/debug-maplibre-gl-native/main-linux-clang8-release-style.html

Thanks. Looking into it.

Note that for posterity it may be useful to attach images to the PR.

2022-07-04 20:09 UTC, wipfli commented
Good idea, @ntadej. Here are some screenshots:

![image](https://user-images.githubusercontent.com/53421382/177212060-5ece7dc9-c39d-46cc-ba8a-fa72a896afda.png)

![image](https://user-images.githubusercontent.com/53421382/177212089-5e7057a5-0455-4188-a3dc-97bd2ad0e1c5.png)

![image](https://user-images.githubusercontent.com/53421382/177212118-9662d413-960a-4179-ba92-6363d87bb7fd.png)

2022-07-04 20:48 UTC, ntadej commented on src/mbgl/util/grid_index.cpp
> -    return util::max(size_t(0), util::min(xCellCount - 1, static_cast<size_t>(std::floor(x * xScale))));
This one happens if `x` is negative. Thinking of a most elegant fix.

I also found another set of warnings that we can enable which will help us detect signed vs unsigned issues. Will investigate how many warnings there are.

2022-07-04 21:03 UTC, ntadej requested changes
Found all the issues. Sorry again for causing them. As I said, will try to enable some more warnings to be able to spot them easier.

2022-07-04 21:03 UTC, ntadej commented on src/mbgl/text/collision_index.cpp
> +            (((-p[1] / p[3] + 1) / 2) * size.height) + viewportPadding
We have to drop precision at the end of calculation:
```suggestion
            static_cast<float>(((p[0] / p[3] + 1) / 2) * size.width + viewportPadding),
            static_cast<float>(((-p[1] / p[3] + 1) / 2) * size.height + viewportPadding)
```

2022-07-04 21:03 UTC, ntadej commented on src/mbgl/text/collision_index.cpp
> +    int minSectionLength = std::min(tileX1 - x1, x2 - tileX1);
This one does not seem to be needed
```suggestion
    float minSectionLength = std::min(tileX1 - x1, x2 - tileX1);
```

2022-07-04 21:07 UTC, ntadej commented on src/mbgl/text/collision_index.cpp
> +    int minSectionLength = std::min(tileX1 - x1, x2 - tileX1);
False alarm. Still investigating this one.

2022-07-05 07:00 UTC, wipfli commented
Don't worry about it. I think the changes in #270 are good and probably we can iron out the typos with the render tests now...

2022-07-05 07:08 UTC, ntadej commented
OK for the last change. Can you:
 - change the type back to `int`
 - add static casts to `int` to each assignment (when calling `std::min`)
 - remove redundant `static_cast`s below when this variable is used.

2022-07-05 09:44 UTC, ntadej approved these changes
Thanks for identifying the problematic files, @wipfli. Looks good to me now.

Note that at least the intersection detection code is very strange and it would be good to understand it.

2022-07-05 09:44 UTC, merged