Add Bazel build file implementation
maplibre/maplibre-gl-native pull request #419
Opened 2022-09-02 16:30 UTC by nvanfleet

This adds bazel build files for iOS. This includes several files in platform/ios, platform/darwin, platform/default, vendor, platform/ios/platform/ios/vendor and root directories. There is a build script in platform/ios/platform/ios/scripts that can be used to build the SDK with options for debug builds, release builds and static and dynamic builds. This (I believe) is the only way to statically build the iOS xcframework.

Relevant to this issue: https://github.com/maplibre/maplibre-gl-native/issues/155

Examples:

`./bazel-package.sh --dynamic --release`

`./bazel-package.sh --dynamic --debug`

`./bazel-package.sh --static --release`

`./bazel-package.sh --static --debug`

Alternately you can use the link option to ensure that the framework is able to link.

`./bazel-package.sh --link`

The default settings if not including any parameters is static release

2022-09-02 16:33 UTC, ntadej requested changes
Thank you for providing this but I think it should be discussed a bit first. Our build system is already very complicated and in my opinion this would just make things even more complicated at this stage. We should probably get our CMake-based build cleaned-up first.

Requesting changes for now so it is not merged by accudent.

2022-09-02 18:17 UTC, roblabs commented on .bazelversion
> +6.0.0-pre.20220630.1
This is fine, but required `brew install bazelisk`

2022-09-02 18:25 UTC, roblabs commented
Benefits of [Bazel](https://bazel.build/) 

1.  Yes, CMake works fine, and is not being replaced, but augmented by Bazel.
2. Benefit of reviewing the new build procedure, #384
3. Static builds.  As @nvanfleet  mentions, "*This (I believe) is the only way to statically build the iOS xcframework.*"
4. I approve this PR

---

I gave the build a spin on a local dev machine.  The GitHub Workflows are currently blocked & being resolved in https://github.com/maplibre/maplibre-gl-native/pull/418.

---

Suggestions

- [ ] Add GitHub Workflow
- [ ] Add docs found here in this issue to an iOS BUILD.md
```bash
# One time install of Bazel
# brew install bazelisk

cd maplibre-gl-native/platform/ios/platform/iOS/scripts
# bazel scripts from above
./bazel-package.sh --dynamic --release
```

---

Output from `./bazel-package.sh --dynamic --release`
> maplibre-gl-native/platform/ios/platform/iOS/scripts 
------ Build type: dynamic Release type: release ------
maplibre-gl-native/platform/ios/platform/iOS/scripts
------ Determining Maplibre version and hash ------
------ Building Maplibre version: 5.12.2 hash: 46a217123a ------
2022/09/02 10:30:08 Downloading https://releases.bazel.build/6.0.0/rolling/6.0.0-pre.20220630.1/bazel-6.0.0-pre.20220630.1-darwin-x86_64...
2022/09/02 10:30:08 Skipping basic authentication for releases.bazel.build because no credentials found in /Users/roblabs/.netrc
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //platform/ios:Mapbox.dynamic (63 packages loaded, 6789 targets configured).
INFO: Found 1 target...
Target //platform/ios:Mapbox.dynamic up-to-date:
  bazel-bin/platform/ios/Mapbox_ios_device.framework.dSYM/Contents/Resources/DWARF/Mapbox_ios_device
  bazel-bin/platform/ios/Mapbox_ios_device.framework.dSYM/Contents/Info.plist
  bazel-bin/platform/ios/Mapbox_ios_simulator.framework.dSYM/Contents/Resources/DWARF/Mapbox_ios_simulator
  bazel-bin/platform/ios/Mapbox_ios_simulator.framework.dSYM/Contents/Info.plist
  bazel-bin/platform/iOS/Mapbox.dynamic.xcframework.zip
INFO: Elapsed time: 1119.707s, Critical Path: 75.65s
INFO: 1705 processes: 111 internal, 1592 darwin-sandbox, 2 local.
INFO: Build completed successfully, 1705 total actions
/maplibre-gl-native/platform/ios/platform/iOS/scripts
Done.
Package will be available in "/bazel-bin/platform/ios/platform/iOS/Mapbox.dynamic.xcframework.zip"````````````

2022-09-07 03:31 UTC, roblabs approved these changes

2022-09-07 03:32 UTC, merged