Fix memory access violation exception in vector_tile_data.cpp
maplibre/maplibre-gl-native pull request #632
Opened 2022-12-22 04:30 UTC by tdcosta100

I was having some random crashes when browsing my map, then I discovered an unhandled exception when calling `mapbox::vector_tile::feature::getGeometries<T>(float scale)` in `VectorTileFeature::getGeometries()`. So I propose a very basic handling of this situation. I don't know if this is the best solution, but no more crashes since then.

2022-12-22 04:49 UTC, acalcutt commented
I wonder if this would help with https://github.com/maplibre/maplibre-gl-native/issues/574

2022-12-22 06:13 UTC, tdcosta100 commented
This PR addresses exactly that exception message.

2022-12-22 17:11 UTC, ntadej commented on src/mbgl/tile/vector_tile_data.cpp
> +    catch(...) {
I agree.

At least you should try-catch the exact line and catch only the known exception.

2022-12-22 17:11 UTC, ntadej requested changes
This should be done more cleanly.

2022-12-23 17:07 UTC, tdcosta100 commented on src/mbgl/tile/vector_tile_data.cpp
> +    catch(...) {
It's not hard to know in this case. It occurs inside `mapbox::vector_tile::getGeometries(float scale)` when a feature point goes outside excent. This is the piece of code that generates the problem:

https://github.com/mapbox/vector-tile/blob/bc2f7f44cdb0d9af2b282ea4a755f85a13ba713a/include/mapbox/vector_tile.hpp#L305-L311

When this exception is thrown, mbgl::VectorTileFeature::lines does not get populated a value, which was the purpose of mbgl::VectorTileFeature::getGeometries(), which leads to the EACCESSVIOLATION.

I wish it was a better handling of this, but still don't know what I could do. But sure I can do a better catching of this specific error. Please check if it's better now.

2022-12-23 17:14 UTC, tdcosta100 commented on src/mbgl/tile/vector_tile_data.cpp
> +    catch(...) {
Please check this comment https://github.com/maplibre/maplibre-gl-native/pull/632#discussion_r1056501395.

Also please check if it's better now with my update.

2022-12-28 15:25 UTC, acalcutt commented
Looks like the build is failing with this new attempt. It gets this error

```
/home/runner/work/maplibre-gl-native/maplibre-gl-native/src/mbgl/tile/vector_tile_data.cpp:48:40: error: catching polymorphic type ‘const class std::runtime_error’ by value [-Werror=catch-value=]
   48 |         catch(const std::runtime_error ex) {
```

2022-12-28 21:59 UTC, tdcosta100 commented
Ooops, my fault. I missed an `&` to have the exception passed by reference and not by value. I hope this error will not appear this time in CI tasks.

2022-12-29 16:34 UTC, acalcutt commented
I created a maplibre release to test this and a tileserver-gl release that includes it. The releases are.
```
@acalcutt/maplibre-gl-native@6.0.2-pre.3
wifidb/tileserver-gl:v5.2.1-pre.3
```

To test this I did the following
1.) downloaded the [test files ](https://bit.ly/serve-tiles) from the tileserver-gl issue https://github.com/maptiler/tileserver-gl/issues/618#issuecomment-1328116302
2.) extract the files into a folder.
3.) create a missing 'icons' folder in the same directory
4.) Go into that directory and run the docker with
        docker run --rm -it -v $(pwd):/data -p 8080:8080 wifidb/tileserver-gl:v5.2.1-pre.3
5.) http://localhost:8080/styles/osm-bright/?raster#15/22.8138/72.7300

With the fix from this PR in place, tileserver-gl no longer crashes and reports a error like this.
```
GET /styles/osm-bright/15/23002/14250.webp 200 3240 - 185.747 ms
mlgl: {
  class: 'ParseTile',
  severity: 'ERROR',
  text: 'Could not get geometries: paths outside valid range of coordinate_type'
}
```
because this fails more gracefully, the page is able to load. I do notice some text clipping, but that could be another issue
![image](https://user-images.githubusercontent.com/3792408/209981452-8c83141e-fab0-44be-a3da-b92b7c47b101.png)

My opinion is this is an improvement and it is nice having it fail more gracefully with an error. It may help with further discovery of the root cause of why those paths might be out of range.

2022-12-30 01:01 UTC, tdcosta100 commented
Nice! The text clipping occurs because when using the map for tile rendering, it needs data from surrounding tiles to properly render labels with anchors outside the tile region, which is not the default for static and tile modes (at least it doesn't work like that for me). My workaround on this is to render a larger region, then clip the resulting image to the tile bounds.

A definitive solution would be clip the features to get inside the extent passed to `getGeometries`, but I fear it will involve some refactoring, or worse, making changes to the vendor library.

2022-12-30 04:10 UTC, acalcutt commented
@ntadej , did these changes satisfy your request for changes?

2022-12-30 06:17 UTC, acalcutt commented
Not to get too off topic, but for the label thing I fixed a similar issue in https://github.com/maplibre/maplibre-gl-native/issues/284 which ended up fixing the switch for tile mode, which tileserver-gl uses. My understanding of tile mode (if you read that first post) is it extends beyond the edges a bit so it can have that extra data from beyond the tile edge. 

Tile mode did indeed fix some labels, but even after that was fixed I also notice clipped labels in relation to https://github.com/maplibre/maplibre-gl-native/issues/479#issuecomment-1352247308 . That issue usually come with an error though that I don;t see here.

2022-12-30 11:17 UTC, ntadej approved these changes
Thanks, looks good to me now!

2022-12-31 00:45 UTC, acalcutt commented
@tdcosta100 , can you rebase this or merge main.

2022-12-31 17:01 UTC, merged

2022-12-31 18:00 UTC, acalcutt commented
@tdcosta100  I should have requested you add something to the changelog before I merged this. Any chance you could submit a new PR with changelog for this?

2023-01-02 09:13 UTC, tdcosta100 commented
@acalcutt, of course I can, yes. Could you provide me an example PR to copy from?

2023-01-02 09:23 UTC, tdcosta100 commented
> Not to get too off topic, but for the label thing I fixed a similar issue in #284 which ended up fixing the switch for tile mode, which tileserver-gl uses. My understanding of tile mode (if you read that first post) is it extends beyond the edges a bit so it can have that extra data from beyond the tile edge.
> 
> Tile mode did indeed fix some labels, but even after that was fixed I also notice clipped labels in relation to [#479 (comment)](https://github.com/maplibre/maplibre-gl-native/issues/479#issuecomment-1352247308) . That issue usually come with an error though that I don;t see here.

My last comment on this offtopic conversation, I promise. The error you described is because internally Maplibre-GL-Native uses fixed 512x512 tile size, and TileServer-GL uses 256x256 tile size, so when you want to render any particular tile, you are rendering just a quarter portion of a bigger tile. When you add a margin or when you come to rounding issues, it warns you that it wasn't expecting more than 1 big tile to be rendered. If you set tile size to 512x512 in TileServer-GL (but then you have to fix the zoom tweak it has), everything goes fine, except some rounding issues sometimes. Because of that, it's better to run TileServer-GL with the renderers set to Static mode instead of Tile Mode. But of course, this is an entirely new discussion.

2023-01-02 16:15 UTC, acalcutt commented
For the CHANGELOG, something in bug fixes like https://github.com/maplibre/maplibre-gl-native/pull/498/files would be great.

For the label issue, maybe we should open a new issue to track it.
In my testing with the tileserver renderer set to static, it causes all sorts of label clipping like
![clipping](https://user-images.githubusercontent.com/3792408/210255989-d30186a7-cd01-4979-8d29-dd2129af1f19.png). Using tile mode fixed those labels. My understanding is that label clipping was one of the reason tile mode was added. Is this a vector vs raster difference?

2023-01-02 17:09 UTC, acalcutt commented
For an example, 

This map is using western-zone-latest.mbtiles from the example https://bit.ly/serve-tiles , you can see the label is clipped.
https://tiles.wifidb.net/styles/western-zone/?raster#15/22.8167/72.7381

However this style that is using a planetiler generated file, the label is fine
https://tiles.wifidb.net/styles/WDB_OSM/?raster#15/22.8167/72.7381

Whats the difference? looking at the example again I though maybe it was a raster, but for sure it is just another vector file.

2023-01-02 19:10 UTC, tdcosta100 commented
> @tdcosta100 I should have requested you add something to the changelog before I merged this. Any chance you could submit a new PR with changelog for this?

Could you please see if it's ok my changelog edit?

https://github.com/maplibre/maplibre-gl-native/pull/645

2023-02-20 16:35 UTC, georgbachmann commented
I have no idea if my problem is related to this or mapbox-libre in general, but the one big thing I changed from my previous release to the latest, is switching from the official mapbox version to this mapbox-libre fork.
I am using the latest version here (iOS 5.13.0) and I am seeing a super strange crash in Firebase with no real hint, except `Fatal Exception: std::runtime_error` and I noticed that all my crashed devices had very little RAM left over.
I have not been able to reproduce this though... this is why I am vaguely asking if that could be releated?!?

As it seems that Mapbox is throwing exceptions like this and as this issue here also is something about memory-access, it might be related?!?

Is your fix @tdcosta100 already merged, right? And is it part of one of the latest iOS release as well?