Refactor CI workflows from paths-ignore -> paths #503
maplibre/maplibre-gl-native pull request #677
Opened 2023-01-10 14:39 UTC by louwers

Closes #503

I will keep an eye to see if CI is running when it should, to see if I missed a file.

If anyone else sees any glaring omissions, let me know.

2023-01-10 14:41 UTC, ntadej requested changes

2023-01-10 14:41 UTC, ntadej commented on .github/workflows/ios-ci.yml
> +      - 'platform/ios/**'
Needs `darwin` as far as I know.

2023-01-10 14:41 UTC, ntadej commented on .github/workflows/macos-ci.yml
> +      - 'platform/ios/**'
Also here.

2023-01-10 14:45 UTC, louwers commented on .github/workflows/ios-ci.yml
> +      - 'platform/ios/**'
Thanks!

2023-01-11 14:07 UTC, birkskyum approved these changes

2023-01-11 14:08 UTC, merged