Pass a std::string instead of function return value
maplibre/maplibre-gl-native pull request #918
Opened 2023-03-20 13:54 UTC by etnav

Building with the option `MBGL_WITH_EGL = ON` on windows and noticed that with the latest repository state `main`, the build failed with following errors:

```
C:\builds\maplibre-gl-native\include\mbgl/util/logging.hpp(70): error C2665: 'mbgl::Log::record': none of the 3 overloads could convert all the argument types
C:\builds\maplibre-gl-native\include\mbgl/util/logging.hpp(78): note: could be 'void mbgl::Log::record(mbgl::EventSeverity,mbgl::Event,int64_t,const std::string &)'
C:\builds\maplibre-gl-native\include\mbgl/util/logging.hpp(66): note: while trying to match the argument list '(mbgl::EventSeverity, mbgl::Event, const char [48], _Ty)'
        with
        [
            _Ty=EGLint
        ]
C:\builds\maplibre-gl-native\include\mbgl/util/logging.hpp(61): note: see reference to function template instantiation 'void mbgl::Log::Record<const char(&)[48],_Ty>(mbgl::EventSeverity,mbgl::Event,const char (&)[48],_Ty &&)' being compiled
        with
        [
            _Ty=EGLint
        ]
C:\builds\maplibre-gl-native\platform\windows\src\headless_backend_egl.cpp(34): note: see reference to function template instantiation 'void mbgl::Log::Error<const char(&)[48],EGLint>(mbgl::Event,const char (&)[48],EGLint &&)' being compiled
```

Seems to be related to the recent changes in this [PR](https://github.com/maplibre/maplibre-gl-native/pull/911).

With the changes done in this PR and suggestions by @louwers  I am again able to build the node binaries on windows.

2023-03-20 14:16 UTC, louwers commented
You left the format string in the second one.

Could you please use


```
#include <sstream>

...

std::ostringstream logMsg;
logMsg << "eglCreateContext() returned error 0x" << std::setw(4) << std::setfill('0') << std::hex << eglGetError();
mbgl::Log::Error(mbgl::Event::OpenGL, logMsg.str());
```

This is a bit cumbersome, but we will be able to use `std::format` soon.

2023-03-20 17:48 UTC, louwers requested changes
See comment.

2023-03-21 08:27 UTC, tdcosta100 commented
Since `platform/windows/src/headless_backend_egl.cpp` was copied from `platform/linux/src/headless_backend_egl.cpp`, the offending piece of code could be:

```c++
            mbgl::Log::Error(mbgl::Event::OpenGL, "eglBindAPI(EGL_OPENGL_ES_API) returned error " +
                             std::to_string(eglGetError()));
```

2023-03-22 21:15 UTC, louwers approved these changes

2023-03-23 12:21 UTC, merged